import Head from "next/head";
import { useState } from "react";

// COMPONENTS
import { Header } from "../components/Header";
import { Timeline } from "../components/Timeline";

import configs from "../../configs.json";

interface PlaylistParams {
  title: string;
  url: string;
  thumb: string;
}

export default function Home() {
  const playlistItems = Object.entries(configs.playlists);
  const playlistCategories = Object.keys(configs.playlists);
  const [selectedCategory, setSelectedCategory] = useState("jogos");

  return (
    <div className="bg-zinc-900 min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header
        githubUser="hemerson-git"
        menuItems={[configs.description, configs.github, configs.name]}
      />

      <main className="px-4">
        <h1 className="text-3xl font-bold text-white mt-2 mb-3">
          Hello, World
        </h1>
      </main>

      <div>
        <ul>
          {playlistCategories.map((playlistCategory, index) => (
            <li key={`${playlistCategory}-${index}`}>
              <button onClick={() => setSelectedCategory(playlistCategory)}>
                {playlistCategory}
              </button>
            </li>
          ))}
        </ul>
      </div>

      {playlistItems.map((playlistItem, index) => {
        return (
          selectedCategory === playlistItem[0] && (
            <Timeline
              key={index}
              category={playlistItem[0]}
              playlists={playlistItem[1] as any as PlaylistParams[]}
            />
          )
        );
      })}
    </div>
  );
}
