import Head from "next/head";
import { useState } from "react";

// COMPONENTS
import { Header } from "../components/Header";
import { Timeline } from "../components/Timeline";

import configs from "../../configs.json";
import { Banner } from "../components/Banner";
import { Favorite } from "../components/Favorite";

interface PlaylistParams {
  title: string;
  url: string;
  thumb: string;
}

export default function Home() {
  const playlistItems = Object.entries(configs.playlists);
  const playlistCategories = Object.keys(configs.playlists);
  const [selectedCategory, setSelectedCategory] = useState("jogos");
  const [searchValue, setSearchValue] = useState("");

  return (
    <div className="bg-zinc-900 min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header
        onChangeSearchValue={setSearchValue}
        githubUser="hemerson-git"
        // menuItems={[configs.description, configs.github, configs.name]}
      />

      <Banner bannerURL="/linus.jpg" />

      <main className="px-4">
        <h1 className="text-3xl font-bold text-gray-100 mb-6">
          {configs.name}
        </h1>

        <section className="flex flex-col mb-4 text-gray-100">
          <h2 className="font-bold text-xl mb-4">Favorites</h2>

          <div className="flex gap-3">
            {configs.favorites.map((favorite) => (
              <Favorite
                thumb={favorite.thumb}
                url={favorite.url}
                key={favorite.url}
              />
            ))}
          </div>
        </section>

        <section className="w-full overflow-hidden">
          {playlistItems.map((playlistItem, index) => (
            <Timeline
              query={searchValue}
              key={index}
              category={playlistItem[0]}
              playlists={playlistItem[1] as any as PlaylistParams[]}
            />
          ))}
        </section>
      </main>

      {/* <div>
        <ul>
          {playlistCategories.map((playlistCategory, index) => (
            <li key={`${playlistCategory}-${index}`}>
              <button onClick={() => setSelectedCategory(playlistCategory)}>
                {playlistCategory}
              </button>
            </li>
          ))}
        </ul>
      </div> */}
    </div>
  );
}
